server.port=8083
spring.application.name=validation-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/validationdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initialize Database on Startup
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true

# ===============================
# Kafka Configuration (Event-Driven)
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=validation-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.sql.init.data-locations=file:init-schema.sql
spring.jpa.defer-datasource-initialization=true

# OpenAPI / Swagger Configuration
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.operationsSorter=method
